exp_name: 'rsna_normal_size256'

dataset: 'rsna'
model: 'denoising_diffusion'

img_size: 256
normal_only: True
num_steps: 100000
batch_size: 8
lr: 0.0001
print_freq: 100
val_freq: 1000
checkpoint_freq: 5000
